#!/bin/sh

set -eu

ARCH="$(uname -m)" export ARCH

get_graboid() {
	[ -f graboid ] && return 0
	case "$ARCH" in
	x86_64)
		curl -L "https://github.com/blacktop/graboid/releases/download/0.15.8/graboid_0.15.8_linux_$ARCH.tar.gz" > graboid.tgz
		tar xzf graboid.tgz graboid
		rm ./graboid*gz
		;;
	*) printf "No builds available for graboid %s, please build manually\n" "$ARCH" ;;
	esac
}

get_proot() {
	[ -f proot ] && return 0
	case "$ARCH" in
	x86_64)
		curl -L "https://github.com/proot-me/proot/releases/download/v5.2.0/proot-v5.2.0-$ARCH-static" > proot
		chmod +x proot
		;;
	*) printf "No builds available for proot %s, please build manually\n" "$ARCH" ;;
	esac
}

get_appimagetool() {
	[ -f "appimagetool-$ARCH.AppImage" ] && return 0
	curl -L "https://github.com/AppImage/AppImageKit/releases/download/continuous/appimagetool-$ARCH.AppImage" > "appimagetool-$ARCH.AppImage"
	chmod +x "appimagetool-$ARCH.AppImage"
}

download() {
	echo "[+] Getting appimagetool..."
	get_appimagetool
	echo "[+] Getting proot..."
	get_proot
	echo "[+] Getting graboid..."
	get_graboid
}

make_image() {
	echo "[+] Building AppDir..."
	mkdir -p AppDir/usr/bin
	mkdir -p AppDir/usr/lib/dockie
	cp AppRun AppDir/
	cp dockie.desktop AppDir/
	cp dockie.png AppDir/
	cp dockie AppDir/usr/bin
	mv proot AppDir/usr/bin
	mv graboid AppDir/usr/bin
	echo "[+] Building AppImage..."
	ARCH="$ARCH" ./appimagetool-"$ARCH".AppImage -v AppDir 
	echo "[+] All done!"
	echo
	echo "You can now use Dockie with ./dockie-$ARCH.AppImage or copy it somewhere in your PATH"
	echo
}

clean() {
	rm -rf AppDir
	rm -f proot
	rm -f graboid*
	rm -f dockie*AppImage
	rm -f appimagetool*
}

case "${1-}" in
clean) clean ;;
dl) download ;;
"") make_image ;;
*) echo 'unrecognised argument' >&2 && exit 1 ;;
esac
