#!/bin/sh

DEFAULT_PREFIX="${PREFIX-/usr/local}"

printf 'Where should dockie be installed? [%s] ' "$DEFAULT_PREFIX"
read -r PREFIX

./configure
make
PREFIX="${PREFIX:-$DEFAULT_PREFIX}" make install ||
	echo 'INSTALL: if you want to install to /usr/local, you might need' \
	'to run the script as root' 2>&1  && exit 1
 
