#!/bin/sh

set -eu

printf "Images source? (lxc or docker) [lxc] "
read -r HUB

case "$HUB" in
docker)
	sed -i 's/get-.*.sh/get-docker.sh/g' Makefile 
	sed -i 's/\t@# cp -p con/\tcp -p con/g' Makefile
	;;
lxc | "" )
	sed -i 's/get-.*.sh/get-lxc.sh/g' Makefile 
	sed -i 's/\tcp -p con/\t@# cp -p con/g' Makefile
	;;
*) echo invalid option >&2 && exit 1 ;;
esac

printf 'Where to install? [%s/.local/bin] ' "$HOME"
read -r PREFIX
: "${PREFIX:=$HOME/.local/bin}"

make 
make PREFIX="$PREFIX" install 
