#!/bin/sh
set -eu

[ "$#" -eq 0 ] &&
	printf 'usage: %s [directory]\n' "$(basename "$0")" &&
	exit 1

DIR="$(cd "$(dirname "$0")" && pwd)"
printf '#!/bin/sh\nexec %s/pocker.sh "$@"\n' "$DIR" >"$1/pocker"
chmod +x "$1/pocker"
